### ISSUE TITLE
yarn run serve 启动失败

### ISSUE THREAD

**Issue by noyyyy** [DappReader/DappReader-v2#5]
yarn 1.22.19
node 16.0
npm 7.10.0

yarn install, yarn run serve 会出现如下报错

```
 ERROR  Failed to compile with 4 errors                                                                                              1:27:39 PM

This dependency was not found:

* naive-ui in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/Menu.vue?vue&type=script&lang=js and 2 others

To install it, you can run: npm install --save naive-ui
```

跑了 `npm install --save naive-ui` 之后就正常了，但就又变成 npm 装包了

**Comment by TiyoSheng** [comment]
可以用yarn add naive-ui代替npm install --save naive-ui

**Comment by noyyyy** [comment]
> 可以用yarn add naive-ui代替npm install --save naive-ui

但实际上没有效果。`naive-ui` 在 package.json 里面，yarn install 的时候统一安装没装上，yarn add naive-ui 也装不上。

我用的 github codespace 来安装的，你也可以复现一下。github codespace 需要先用 `nvm use xxx` 改一下 node 版本
